import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BasketProvider } from "@/context/BasketContext";
import { SabawashProvider } from "@/context/SabawashCheckout";
import { RideProvider } from "@/context/RideContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sabaha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <SabawashProvider>
          <BasketProvider>
            <RideProvider>{children}</RideProvider>
          </BasketProvider>
        </SabawashProvider>
      </body>
    </html>
  );
}
